### ISSUE TITLE
Issues using it in negative mode (APTS-labeled glycans)

### ISSUE THREAD

**Issue by GSMKammeijer** [Tarskin/LaCyTools#28]
While trying to use LaCyTools errors occured while trying to generate the combined results (just after one summed spectrum generation). The files are send via wetransfer.

**Comment by Tarskin** [comment]
The above bug is due to the filepath exceeding the maximum length specified by the Win32 API of 255 characters. I am currently investigating how we can fix this in the program using path normalization or similar methods.

**Comment by Tarskin** [comment]
Additionally, the above issue showed that if there are other '.raw' files in the folder (such as the raw data of a specific instrument) the program also stops.

**Comment by Tarskin** [comment]
The fix for the filelength is as follows:

```
(old, new) = os.path.split(self.inputFile)
old = os.path.abspath(old)
new = os.path.splitext(new)[0]
new = "sumSpectrum_"+str(i)+"_"+str(new)+".xy"
new = os.path.join(old,new)
outFile = "\\\\?\\"+new
```

Regarding the reading of raw instrument data, I added a try: and except StopIteration to the combineResults() function which should address any '.raw' files which can't be opened by LaCyTools.
