### ISSUE TITLE
Isotopic pattern relative intensities give nonsensical values in the analyte.ref for intact protein fragments ca. 25 kDa

### ISSUE THREAD

**Issue by DhunShafir** [Tarskin/LaCyTools#31]
I was trying to calculate the isotopic patterns of a protein fragment (ca. 25 kDa).

While it looks like I am getting the correct masses of the most abundant isotopes, the relative intensity is nonsensical (see attached analytes.ref). 

For example, m/z 1190.30 should be the most abundant isotope according to "http://www.envipat.eawag.ch/index.php", which matches the fact that 1190.30 is also the middle isotope calculated by LaCyTools (at this size a Gaussian-like distribution around the most abundant isotope is logical). 

I also attached the LaCyTools script I ran, in case I added the error when I added the building block.

[Issue 180406.zip](https://github.com/Tarskin/LaCyTools/files/1883448/Issue.180406.zip)

**Comment by Tarskin** [comment]
This issue does not appear when using the Isotopic Pattern calculator (as supplied with MassyTools).

**Comment by Tarskin** [comment]
LaCyTools correctly calculates the isotopic pattern for 8 IgG1 molecules, but at 9 IgG1 (>10 kDa) molecules the pattern goes wrong.

**Comment by Tarskin** [comment]
This bug will be closed once the fix has been verified by two separate users.

**Comment by Tarskin** [comment]
This fix has been verified by Guinevere SM Kammeijer.

**Comment by Tarskin** [comment]
This bug will be closed as the fix has been verified by several sources.
