### ISSUE TITLE
Datapoints per 1 m/z

### ISSUE THREAD

**Issue by GSMKammeijer** [Tarskin/LaCyTools#44]
**Describe the bug**
When a file is used that has analytes varying from 10+ up to 25+ it will be hard to have the correct setting for the datapoints:

- If not enough datapoints are selected (less than in the original dataset), we observe peaksplitting.
- In the case of too many datapoints we observe zeros

As the number of datapoints differ between low m/z and high m/z values it is hard to define a setting that applies for both regions.

**Comment by Tarskin** [comment]
This issue should be resolved with the dynamic_summing branch, can you confirm?

**Comment by GSMKammeijer** [comment]
Confirmed :)
